name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm run test:prod

#      - name: Run lint
#        run: npm run lint

  deploy-production:
    needs: build
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v3.5.3

        - name: Setup SSH
          uses: webfactory/ssh-agent@v0.8.0
          with:
            ssh-private-key: ${{ secrets.PRODUCTION_SSH_PRIVATE_KEY }}

        - name: Install SSH client
          run: |
              sudo apt-get update
              sudo apt-get install -y openssh-client

        - name: Deploy to Production
          run: |
            ssh -o StrictHostKeyChecking=no -p ${{ secrets.PRODUCTION_SSH_PORT }} ${{ secrets.PRODUCTION_SSH_USERNAME }}@${{ secrets.PRODUCTION_SSH_HOST }} 'cd ${{ vars.REPO_PATH }} && sudo git checkout main && sudo git pull && sudo ng build && sudo ng build && sudo cp dist/* -t ${{ vars.OUTPUT_DIR_PROD }} -r && sudo rm -rf dist/'
