name: Deploy Development

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm run test:prod

#      - name: Run lint
#        run: npm run lint
  
  deploy-prod:
    needs: build
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v3.5.3
        
        - name: Setup SSH
          uses: webfactory/ssh-agent@v0.8.0
          with:
            ssh-private-key: ${{ secrets.DEVELOPMENT_SSH_PRIVATE_KEY }}

        - name: Install SSH client
          run: |
              sudo apt-get update
              sudo apt-get install -y openssh-client

        - name: Deploy to Development
          run: |
            ssh -o StrictHostKeyChecking=no -p ${{ secrets.DEVELOPMENT_SSH_PORT }} ${{ secrets.DEVELOPMENT_SSH_USERNAME }}@${{ secrets.DEVELOPMENT_SSH_HOST }} 'cd ${{ vars.REPO_PATH }} && sudo git checkout main && sudo git pull && sudo ng build && sudo mv dist/* ${{ vars.OUTPUT_DIR_DEV }}'